<a href="https://colab.research.google.com/github/duyqu-chan/CS231n/blob/master/CS231_Python_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [CS231 PYTHON TUTORIAL](http://cs231n.github.io/python-numpy-tutorial/)

## Basic Data Types

+ **Numbers**

In [0]:
x = 3
print(type(x)) #<class 'int'>
print(x) #3
print(x+1) #4
print(x-1) #2
print(x*2) #6
print(x**2) #9
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


+ **Boolean**

In [0]:
t = True
f = False
print(type(t)) #<class 'bool'>
print(t and f) #False
print(t or f) #True
print(not t) #False
print(t != f) #True


<class 'bool'>
False
True
False
True


+ **Strings**

In [0]:
hello = "hello"
world = "world"
print(hello) #hello
print(len(hello)) #5
hw = hello + " " + world 
print(hw) #hello world
hw12 = "%s %s %d" % (hello, world, 12) #hello world 12
print(hw12)

hello
5
hello world
hello world 12


In [0]:
s = "hello"
print(s.capitalize()) #Hello
print(s.upper()) #HELLO
print(s.rjust(7))#"  hello"
print(s.ljust(7))#"hello  "
print(s.center(7))#" hello "
print(s.replace('l', '(ell)')) #he(ell)(ell)o
print('  world '.strip()) #world

Hello
HELLO
  hello
hello  
 hello 
he(ell)(ell)o
world


+ **Containers**
      Lists, Dictionaries, Sets

 + **Lists**
 
      A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [0]:
xs = [3, 1, 2]
print(xs, xs[2])  #[3, 1, 2] 2
print(xs[-1]) #prints last element: 2
print(xs[-2]) #prints 2nd element from end 1
print(xs[-0]) #prints 1st element since -0 = 0 
xs[2] = 'foo'  
print(xs) #[3, 1, 'foo']
xs.append('bar')
print(xs) #[3, 1, 'foo', 'bar']
x = xs.pop() #x="bar"
print(x,xs) #bar [3, 1, 'foo']

[3, 1, 2] 2
2
1
3
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


+ *Slicing*

In [0]:
nums = list(range(10))
print(nums) #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(nums[2:4])  #[2, 3]
print(nums[2:])  #a slice to the end: [2, 3, 4, 5, 6, 7, 8, 9]
print(nums[:2]) # a slice till 2nd element: [0, 1]
print(nums[:]) #whole list
print(nums[:-1]) # a slice till last element: [0, 1, 2, 3, 4, 5, 6, 7, 8]
print(nums[:-3]) # [0, 1, 2, 3, 4, 5, 6]
nums[2:4] = [8, 9]
print(nums) #[0, 1, 8, 9, 4, 5, 6, 7, 8, 9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 8, 9, 4, 5, 6, 7, 8, 9]


+  *Loops*

In [0]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal) #cat
                  #dog
                  #monkey

cat
dog
monkey


In [0]:
#enumarate
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey


+ *List Comprehensions*

In [0]:
nums = range(10)
print(nums) #range(0, 10)
squares = [x**2 for x in nums]
print(squares) #[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

range(0, 10)
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [0]:
#conditional comprehension
cubes = [x**3 for x in nums if x%3 ==0]
print(cubes) #[0, 27, 216, 729]

[0, 27, 216, 729]


+ **Dictionaries**
      key-value pairs

In [0]:
d = {"cat": "unpredictable", "dog": "loyal", "rabbit": "coward"}
print(d["cat"]) #unpredictable
print("dog" in d) #True
d["pig"] = "noisy" #{'cat': 'unpredictable', 'dog': 'loyal', 'rabbit': 'coward', 'pig': 'noisy'}
print(d)
print(d.get('monkey')) #None
print(d.get('monkey', 'N/A'))#N/A
del d["pig"]
print(d) #{'cat': 'unpredictable', 'dog': 'loyal', 'rabbit': 'coward'}
print(d.get('pig', 'N/A'))#N/A 

unpredictable
True
{'cat': 'unpredictable', 'dog': 'loyal', 'rabbit': 'coward', 'pig': 'noisy'}
None
N/A
{'cat': 'unpredictable', 'dog': 'loyal', 'rabbit': 'coward'}
N/A


+ *Loops*

In [0]:
d = {"human":2, "spider":8, "bird":2, "donkey":4}
for animal in d:
  legs = d[animal]
  print('A %s has %d legs' % (animal, legs))

A human has 2 legs
A spider has 8 legs
A bird has 2 legs
A donkey has 4 legs


+ *Dictionary Comprehensions*

In [0]:
nums = range(10)
odd2cube = {x: x**3 for x in nums if x%2 != 0}
print(odd2cube) #{1: 1, 3: 27, 5: 125, 7: 343, 9: 729}

{1: 1, 3: 27, 5: 125, 7: 343, 9: 729}


+ **Sets**

In [0]:
s = {"cat", "dog", "bird"}
print(s) #{'dog', 'bird', 'cat'}
print("cat" in s) #True
print("elephant" in s) #False
print(len(s)) #3
s.add("fish")
print(s) #{'dog', 'fish', 'bird', 'cat'}
s.remove("dog")
print(s) #{'fish', 'bird', 'cat'}

{'dog', 'bird', 'cat'}
True
False
3
{'dog', 'fish', 'bird', 'cat'}
{'fish', 'bird', 'cat'}


*Loops*

Since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [0]:
for idx, animal in enumerate(s):
  print("%d: %s" %(idx+1,animal))
  

1: fish
2: bird
3: cat


*Set Comprehensions*

In [0]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(100)}
print(nums)  # {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
nums2 = {(sqrt(x)) for x in range(100)}
print(nums2) #{0.0, 1.0, 2.0, 1.7320508075688772, 1.4142135623730951, ...}

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0.0, 1.0, 2.0, 1.7320508075688772, 1.4142135623730951, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795, 3.3166247903554, 3.4641016151377544, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 4.47213595499958, 5.196152422706632, 5.744562646538029, 6.4031242374328485, 6.557438524302, 7.0710678118654755, 7.416198487095663, 7.615773105863909, 7.810249675906654, 8.888194417315589, 8.06225774829855, 8.12403840463596, 8.94427190999916, 8.831760866327848, 9.055385138137417, 9.1104335791443, 9.273618495495704, 9.643650760992955, 4.242640687119285, 4.358898943540674, 6.082762530298219, 6.164414002968976, 7.280109889280518, 7.483314773547883, 3.605551275463989, 5.291502622129181, 5.830951894845301, 6.244997998398398, 6.928203230275509, 7.745966692414834, 7.874007874011811, 8.48528137423857, 8.717797887081348, 8.306623862918075, 9.16515138991168, 9.433981132056603, 9.746794344808963, 5.385164807134504, 5.5677643628300215, 6.324555320

+ **Tuples**

  A tuple is an (immutable) ordered list of values.

In [0]:
t = (5,6) #create a tuple
t = (7,8) #recreate
t[0]=0 #try to mutate: TypeError: 'tuple' object does not support item assignment

True


TypeError: ignored

Tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. 

In [0]:
d = {(x, x + 1): x for x in range(10)} 
print(d) #{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
print(d[(1, 2)]) #1

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
1


## Functions

In [0]:
def greet(name, loud = False):
  s = "Hello" + " " + name.capitalize() 
  if loud:
    s += "!"
    print(s.upper())
  else:
    print(s)
    
greet("duygu")
greet("duygu", loud=True)

Hello Duygu
HELLO DUYGU!


## Classes

In [0]:
class Greeter(object):
  
  def __init__(self,name):
    self.name = name
    
  def greet(self, loud = False):
    s = "Hello" + " " + self.name.capitalize() 
    if loud:
      s += "!"
      print(s.upper())
    else:
      print(s)
      
g = Greeter("duygu")
g.greet(loud=True)

HELLO DUYGU!


## NumPy

In [0]:
import numpy as np

### Arrays

In [0]:
a = np.array([1, 2, 3])
print(type(a)) #<class 'numpy.ndarray'>
print(a.shape) #(3,)
print(a[0]) #1
a[0] = 1000
print(a) #[1000    2    3]

<class 'numpy.ndarray'>
(3,)
1
[1000    2    3]


In [0]:
b = np.array([[1,2,3],[4,5,6]]) 
print(b) #[[1 2 3]
         # [4 5 6]]
print(b.shape) #(2, 3)
print(b[0, 0], b[0, 1], b[1, 0]) #1 2 4


[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


In [0]:
a = np.full([3,3],10)
print(a)
b = np.random.random([3,3])
print(b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[0.52730461 0.99989797 0.13722231]
 [0.32621847 0.4268877  0.2139858 ]
 [0.3178425  0.05205959 0.35190912]]


#### Array Indexing

+ **Slicing**

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [0]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


+ **Integer array indexing**

In [0]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]" since it is equivalent to a(0,0), a(1,1), a(2,0)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


Selecting or mutating one element from each row of a matrix while integer array indexing

In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
